// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBELPEyGzJ1FGRP97210Lud5gz825IEPWs',
    appId: '1:592498708690:web:82c49c99458d43460e5d0b',
    messagingSenderId: '592498708690',
    projectId: 'stu-app-34986',
    authDomain: 'stu-app-34986.firebaseapp.com',
    databaseURL: 'https://stu-app-34986-default-rtdb.firebaseio.com',
    storageBucket: 'stu-app-34986.appspot.com',
    measurementId: 'G-BPPZ5TR30R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgRu6koCwPde_1LGTdwFzSfZHXxLKxN_U',
    appId: '1:592498708690:android:a6a26e0d86fe79300e5d0b',
    messagingSenderId: '592498708690',
    projectId: 'stu-app-34986',
    databaseURL: 'https://stu-app-34986-default-rtdb.firebaseio.com',
    storageBucket: 'stu-app-34986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs0rPJ9_sfoVdpWOh7XuapvY08pUWKUXA',
    appId: '1:592498708690:ios:51d40f6a56f8a56a0e5d0b',
    messagingSenderId: '592498708690',
    projectId: 'stu-app-34986',
    databaseURL: 'https://stu-app-34986-default-rtdb.firebaseio.com',
    storageBucket: 'stu-app-34986.appspot.com',
    iosClientId: '592498708690-9qktnomq50a374s5rjqgp61tb474co57.apps.googleusercontent.com',
    iosBundleId: 'com.example.conductor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs0rPJ9_sfoVdpWOh7XuapvY08pUWKUXA',
    appId: '1:592498708690:ios:51d40f6a56f8a56a0e5d0b',
    messagingSenderId: '592498708690',
    projectId: 'stu-app-34986',
    databaseURL: 'https://stu-app-34986-default-rtdb.firebaseio.com',
    storageBucket: 'stu-app-34986.appspot.com',
    iosClientId: '592498708690-9qktnomq50a374s5rjqgp61tb474co57.apps.googleusercontent.com',
    iosBundleId: 'com.example.conductor',
  );
}
